### ISSUE TITLE
Runtime error: undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by MrCsabaToth** [HarlemSquirrel/amdgpu-fan-rb#2]
```
# gem install amdgpu_fan
Fetching amdgpu_fan-0.5.0.gem
Successfully installed amdgpu_fan-0.5.0
Parsing documentation for amdgpu_fan-0.5.0
Installing ri documentation for amdgpu_fan-0.5.0
Done installing documentation for amdgpu_fan after 0 seconds
1 gem installed
# amdgpu_fan status
Traceback (most recent call last):
	9: from /usr/local/bin/amdgpu_fan:23:in `<main>'
	8: from /usr/local/bin/amdgpu_fan:23:in `load'
	7: from /var/lib/gems/2.7.0/gems/amdgpu_fan-0.5.0/bin/amdgpu_fan:6:in `<top (required)>'
	6: from /usr/lib/ruby/vendor_ruby/thor/base.rb:466:in `start'
	5: from /usr/lib/ruby/vendor_ruby/thor.rb:387:in `dispatch'
	4: from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
	3: from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	2: from /var/lib/gems/2.7.0/gems/amdgpu_fan-0.5.0/lib/amdgpu_fan/cli.rb:57:in `status'
	1: from /var/lib/gems/2.7.0/gems/amdgpu_fan-0.5.0/lib/amdgpu_fan/cli.rb:57:in `map'
/var/lib/gems/2.7.0/gems/amdgpu_fan-0.5.0/lib/amdgpu_fan/connector.rb:47:in `display_name': undefined method `strip' for nil:NilClass (NoMethodError)
```
The hardware has a Ryzen 7 2700 CPU with a Radeon RX Vega 56 (8GB HBM2) GPU. (Acer Predator Helios 500 Ryzen)

```
# lsmod | grep amd
edac_mce_amd           32768  0
kvm_amd               110592  0
kvm                   798720  1 kvm_amd
amdgpu               5021696  17
gpu_sched              36864  1 amdgpu
ttm                   122880  1 amdgpu
drm_kms_helper        233472  1 amdgpu
drm                   585728  12 gpu_sched,drm_kms_helper,amdgpu,ttm
i2c_algo_bit           16384  1 amdgpu
mfd_core               20480  1 amdgpu
ccp                   102400  1 kvm_amd
gpio_amdpt             20480  0
gpio_generic           16384  1 gpio_amdpt
```

```
# lspci
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) I/O Memory Management Unit
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:01.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) PCIe GPP Bridge
00:01.3 PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) PCIe GPP Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:03.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:03.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) PCIe GPP Bridge
00:04.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:07.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:07.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Internal PCIe GPP Bridge 0 to Bus B
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Internal PCIe GPP Bridge 0 to Bus B
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 59)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 7
01:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM961/PM961
02:00.0 USB controller: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset USB 3.1 XHCI Controller (rev 01)
02:00.1 SATA controller: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset SATA Controller (rev 01)
02:00.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Bridge (rev 01)
03:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
03:01.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
03:08.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
04:00.0 Ethernet controller: Qualcomm Atheros Killer E2500 Gigabit Ethernet Controller (rev 10)
05:00.0 Network controller: Intel Corporation Wireless-AC 9260 (rev 29)
07:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1470 (rev c7)
08:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1471
09:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] (rev c7)
09:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 HDMI Audio [Radeon Vega 56/64]
0a:00.0 Non-Essential Instrumentation [1300]: Advanced Micro Devices, Inc. [AMD] Zeppelin/Raven/Raven2 PCIe Dummy Function
0a:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Platform Security Processor
0a:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Zeppelin USB 3.0 Host controller
0b:00.0 Non-Essential Instrumentation [1300]: Advanced Micro Devices, Inc. [AMD] Zeppelin/Renoir PCIe Dummy Function
0b:00.2 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 51)
0b:00.3 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) HD Audio Controller
```

```
# uname -a
Linux asus 5.5.0-2-amd64 #1 SMP Debian 5.5.17-1 (2020-04-15) x86_64 GNU/Linux
```

The distribution is a `Devuan GNU/Linux 4 (chimaera/ceres)`.

**Comment by HarlemSquirrel** [comment]
Ah, it looks like reading the display name from EDID didn't work out. 

Can you share the binary EDID file(s) for the connected displays? They should be in files like these:
```
/sys/class/drm/card0/card0-*/edid
```

**Comment by MrCsabaToth** [comment]
Gotcha, I haven't dig into the call stack. Here are the EDIDs: https://drive.google.com/open?id=15KE_-7qtIlILu8DicwRIvCkv4pXq08Zn

eDP-1 is the native display, an AUO B173HAN03.2
HDMI-A-1 is a HDMI connected GeChic OnLap 1503

I only renamed the edid files so they wont' collide by name. Interesting that the GeChic's edid is 256 byte vs the native display's 128 byte.

**Comment by HarlemSquirrel** [comment]
OK thanks, will take a look in a bit.

**Comment by HarlemSquirrel** [comment]
If you are able to test out the above branch I think that should fix the issue for you.

**Comment by MrCsabaToth** [comment]
Looks like it works!
```
~/repos/amdgpu-fan-rb/bin$ ./amdgpu_fan connectors
DP 1:	disconnected
DP 2:	disconnected
DP 3:	disconnected
HDMI 1:	Onlap1503
 1:	AUO B173HAN03.2
~/repos/amdgpu-fan-rb/bin$ ./amdgpu_fan status
👾 GPU:      Acer Incorporated [ALI] Vega 10 XL/XT [Radeon RX Vega 56/64]
📄 vBIOS:    SWBRT36554.001
📺 Displays: Onlap1503,AUO B173HAN03.2
⏰ Clocks:   150Mhz Core, 800Mhz Memory
💾 Memory:   8176 MiB
🌀 Fan:      auto mode running at 0 rpm (0%)
🌞 Temp:     44.0°C
⚡ Power:    BOOTUP_DEFAULT profile in performance mode using 19.0 / 120.0 Watts (16%)
⚖  Load:     [                    ]00%
```

**Comment by HarlemSquirrel** [comment]
Ah cool. It looks like the connectors didn't properly show the type for the AUO display. 
What folders do you have in `/sys/class/drm/card0/`?

**Comment by MrCsabaToth** [comment]
That's the native display of the laptop, it's the `eDP-1`:
```
# ls /sys/class/drm/card0/
card0-DP-1  card0-DP-2	card0-DP-3  card0-eDP-1  card0-HDMI-A-1  dev  device  power  subsystem	uevent
```

**Comment by HarlemSquirrel** [comment]
OK cool, I pushed a small update that should fix that. Can you try once more?

**Comment by MrCsabaToth** [comment]
```
~/repos/amdgpu-fan-rb/bin$ ./amdgpu_fan connectors
DP 1:	disconnected
DP 2:	disconnected
DP 3:	disconnected
HDMI 1:	Onlap1503
eDP 1:	AUO B173HAN03.2
~/repos/amdgpu-fan-rb/bin$ ./amdgpu_fan status
👾 GPU:      Acer Incorporated [ALI] Vega 10 XL/XT [Radeon RX Vega 56/64]
📄 vBIOS:    SWBRT36554.001
📺 Displays: Onlap1503, AUO B173HAN03.2
⏰ Clocks:   150Mhz Core, 800Mhz Memory
💾 Memory:   8176 MiB
🌀 Fan:      auto mode running at 0 rpm (0%)
🌞 Temp:     47.0°C
⚡ Power:    BOOTUP_DEFAULT profile in performance mode using 21.0 / 120.0 Watts (18%)
⚖  Load:     [***                 ]17%
```

**Comment by MrCsabaToth** [comment]
I'm learning! I haven't ever seen this Regex trick: `[A-z]` is `[A-Za-z]`
